INSERT INTO PUB(ID, PUB_NAME, LINK_MORE_INFO, HAS_FREE_PARKING, TODDLER_FRIENDLY, HAS_GOOD_BEER, TEENAGER_FRIENDLY)
VALUES (1, "Het Anker", "www.hetanker.be", true, false, true, false);

INSERT INTO PUB(ID, PUB_NAME, LINK_MORE_INFO, HAS_FREE_PARKING, TODDLER_FRIENDLY, HAS_GOOD_BEER, TEENAGER_FRIENDLY)
VALUES (2, "'t Schuurke'", "www.schuurke.be", true, false, true, true);

INSERT INTO PUB(ID, PUB_NAME, LINK_MORE_INFO, HAS_FREE_PARKING, TODDLER_FRIENDLY, HAS_GOOD_BEER, TEENAGER_FRIENDLY)
VALUES (3, "De zwaan", "www.dezwaan.be", true, true, false, true);

INSERT INTO PUB(ID, PUB_NAME, LINK_MORE_INFO, HAS_FREE_PARKING, TODDLER_FRIENDLY, HAS_GOOD_BEER, TEENAGER_FRIENDLY)
VALUES (4, "De Ton", "www.hetanker.be", false, true, true, true);
